// This file is generated by Astro DB
declare module "astro:db" {
  export const User: import("@astrojs/db/runtime").Table<
    "User",
    {
      id: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "id";
          collection: "User";
          primaryKey: true;
        };
      };
    }
  >;
  export const Session: import("@astrojs/db/runtime").Table<
    "Session",
    {
      id: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "id";
          collection: "Session";
          primaryKey: true;
        };
      };
      expiresAt: {
        type: "date";
        schema: {
          optional: false;
          unique: false;
          deprecated: false;
          name: "expiresAt";
          collection: "Session";
        };
      };
      userId: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "userId";
          collection: "Session";
          primaryKey: false;
          optional: false;
          references: {
            type: "text";
            schema: {
              unique: false;
              deprecated: false;
              name: "id";
              collection: "User";
              primaryKey: true;
            };
          };
        };
      };
    }
  >;
  export const Artist: import("@astrojs/db/runtime").Table<
    "Artist",
    {
      createdAt: {
        type: "date";
        schema: {
          optional: false;
          unique: false;
          deprecated: false;
          name: "createdAt";
          collection: "Artist";
          default: { __serializedSQL: true; sql: "CURRENT_TIMESTAMP" };
        };
      };
      id: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "id";
          collection: "Artist";
          primaryKey: true;
        };
      };
      name: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "name";
          collection: "Artist";
          primaryKey: false;
          optional: false;
        };
      };
      sid: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "sid";
          collection: "Artist";
          primaryKey: false;
          optional: true;
        };
      };
      userId: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "userId";
          collection: "Artist";
          primaryKey: false;
          optional: false;
          references: {
            type: "text";
            schema: {
              unique: false;
              deprecated: false;
              name: "id";
              collection: "User";
              primaryKey: true;
            };
          };
        };
      };
    }
  >;
  export const Album: import("@astrojs/db/runtime").Table<
    "Album",
    {
      id: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "id";
          collection: "Album";
          primaryKey: true;
        };
      };
      artistId: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "artistId";
          collection: "Album";
          primaryKey: false;
          optional: false;
          references: {
            type: "text";
            schema: {
              unique: false;
              deprecated: false;
              name: "id";
              collection: "Artist";
              primaryKey: true;
            };
          };
        };
      };
      createdAt: {
        type: "date";
        schema: {
          optional: false;
          unique: false;
          deprecated: false;
          name: "createdAt";
          collection: "Album";
          default: { __serializedSQL: true; sql: "CURRENT_TIMESTAMP" };
        };
      };
      sid: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "sid";
          collection: "Album";
          primaryKey: false;
          optional: true;
        };
      };
      title: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "title";
          collection: "Album";
          primaryKey: false;
          optional: false;
        };
      };
      userId: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "userId";
          collection: "Album";
          primaryKey: false;
          optional: false;
          references: {
            type: "text";
            schema: {
              unique: false;
              deprecated: false;
              name: "id";
              collection: "User";
              primaryKey: true;
            };
          };
        };
      };
      year: {
        type: "number";
        schema: {
          unique: false;
          deprecated: false;
          name: "year";
          collection: "Album";
          primaryKey: false;
          optional: true;
        };
      };
      release: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "release";
          collection: "Album";
          primaryKey: false;
          optional: true;
        };
      };
      covers: {
        type: "json";
        schema: {
          optional: true;
          unique: false;
          deprecated: false;
          name: "covers";
          collection: "Album";
        };
      };
    }
  >;
  export const Review: import("@astrojs/db/runtime").Table<
    "Review",
    {
      id: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "id";
          collection: "Review";
          primaryKey: true;
        };
      };
      albumId: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "albumId";
          collection: "Review";
          primaryKey: false;
          optional: false;
          references: {
            type: "text";
            schema: {
              unique: false;
              deprecated: false;
              name: "id";
              collection: "Album";
              primaryKey: true;
            };
          };
        };
      };
      createdAt: {
        type: "date";
        schema: {
          optional: false;
          unique: false;
          deprecated: false;
          name: "createdAt";
          collection: "Review";
          default: { __serializedSQL: true; sql: "CURRENT_TIMESTAMP" };
        };
      };
      rate: {
        type: "number";
        schema: {
          unique: false;
          deprecated: false;
          name: "rate";
          collection: "Review";
          primaryKey: false;
          optional: false;
        };
      };
      text: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "text";
          collection: "Review";
          primaryKey: false;
          optional: false;
        };
      };
      userId: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "userId";
          collection: "Review";
          primaryKey: false;
          optional: false;
          references: {
            type: "text";
            schema: {
              unique: false;
              deprecated: false;
              name: "id";
              collection: "User";
              primaryKey: true;
            };
          };
        };
      };
    }
  >;
  export const Visit: import("@astrojs/db/runtime").Table<
    "Visit",
    {
      id: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "id";
          collection: "Visit";
          primaryKey: true;
        };
      };
      albumId: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "albumId";
          collection: "Visit";
          primaryKey: false;
          optional: false;
          references: {
            type: "text";
            schema: {
              unique: false;
              deprecated: false;
              name: "id";
              collection: "Album";
              primaryKey: true;
            };
          };
        };
      };
      createdAt: {
        type: "date";
        schema: {
          optional: false;
          unique: false;
          deprecated: false;
          name: "createdAt";
          collection: "Visit";
          default: { __serializedSQL: true; sql: "CURRENT_TIMESTAMP" };
        };
      };
      userId: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "userId";
          collection: "Visit";
          primaryKey: false;
          optional: false;
          references: {
            type: "text";
            schema: {
              unique: false;
              deprecated: false;
              name: "id";
              collection: "User";
              primaryKey: true;
            };
          };
        };
      };
    }
  >;
}
